// mod_16_Frameworks_React/mod_16-1_React/my-app/src/App.js
import logo from './logo.svg';
import './App.css';
// import {useState} from 'react'
// import {React} from 'react'
import React from 'react'
import Count from './components/Count';

class App extends React.Component {

    constructor() {
        super();
        this.state = {count: 0, items: []};
    }

    // items = [
    //     {
    //         number: 4,
    //         text: 'Hello world 4'
    //     },
    //     {
    //         number: 5,
    //         text: 'Hello world 5'
    //     },
    //     {
    //         number: 6,
    //         text: 'Hello world 6'
    //     },
    // ];

    // constructor() {
    //     super();
    //     this.state = {count: 0, myCount: 10};
    // }

    // changeCount = () => {
    //     this.setState({
    //         count: this.state.count + 1
    //     });
    // };
    // changeCount() {
    //     this.setState({
    //         count: this.state.count + 1
    //     });
    // };
    // changeCount() {
    //     this.setState((oldState) => ({
    //         count: oldState.count + 1
    //     }));
    // };

    // changeMyCount() {
    //     this.setState({
    //         myCount: this.state.myCount + 1
    //     });
    // }

    // changeMyCount() {
    //     this.setState((oldState) => ({
    //         myCount: oldState.myCount + 1
    //     }));
    // }
    addCount() {

        this.setState((prevState) => {
            const number = this.state.items.length > 0 ? (this.state.items[this.state.items.length - 1].number + 1) : 1;

            return {
                items: [...prevState.items, {
                    number: number,
                    text: `Hello world ${number}`
                }]
            }
        })
    };

    onCountChangeHandler(newCountValue) {
        // console.log(`Value for ${countNumber} changed to ${newCountValue}`);
        this.setState({count: newCountValue});
    }


    render() {
        console.log(1);

        return (

            <div className="App">
                <header className="App-header">
                    <img src={logo} className="App-logo" alt="logo"/>
                    <p>Edit <code>src/App.js</code> and save to reload.</p>
                    {/*<p>Count is {this.state.count}</p>*/}
                    {/*/!*<button onClick={this.changeCount}>click me</button>*!/*/}
                    {/*<button onClick={this.changeCount.bind(this)}>click me</button>*/}
                    <Count initialCount={0} number={<div>1</div>} text={'Hello world 1'}
                        // onCountChange={this.onCountChangeHandler}
                           onCountChange={this.onCountChangeHandler.bind(this)}
                           count={this.state.count}
                    >
                    </Count>
                    <Count initialCount={4} number={1}
                        // onCountChange={this.onCountChangeHandler}>
                           onCountChange={this.onCountChangeHandler.bind(this)}
                           count={this.state.count}>
                        <div>2</div>
                    </Count>
                    <Count number={<div>3</div>} text={'Hello world 3'}
                        // onCountChange={this.onCountChangeHandler}>
                           onCountChange={this.onCountChangeHandler.bind(this)}
                           count={this.state.count}>
                    </Count>

                    {this.state.items.map(item => (
                        <Count number={item.number} text={item.text} key={item.number}
                               onCountChange={this.onCountChangeHandler.bind(this)}
                               count={this.state.count}>
                        </Count>
                    ))}

                    <div>
                        <button onClick={this.addCount.bind(this)}>Add new Count</button>
                    </div>
                    {/*<p>Count is {this.state.myCount}</p>*/}
                    {/*<button onClick={this.changeMyCount.bind(this)}>click me</button>*/}
                    {/*<button onClick={() => {*/}
                    {/*    this.changeCount()*/}
                    {/*}}>click me</button>*/}
                    <a
                        className="App-link"
                        href="https://reactjs.org"
                        target="_blank"
                        rel="noopener noreferrer">
                        Learn React
                    </a>
                </header>
            </div>
        )
    };

    componentDidMount() {
        //backend request

        this.setState({
            items: [
                {
                    number: 4,
                    text: 'Hello world 4'
                },
                {
                    number: 5,
                    text: 'Hello world 5'
                },
                {
                    number: 6,
                    text: 'Hello world 6'
                },
            ]
        })
    }
}

// function App() {
//     const [count, setCount] = useState(0);
//
//     function changeCount() {
//         setCount(count + 1);
//     }
//
//     return (
//         <div className="App">
//             <header className="App-header">
//                 <img src={logo} className="App-logo" alt="logo"/>
//                 <p>
//                     Edit <code>src/App.js</code> and save to reload.
//                 </p>
//                 <p>Count is {count}</p>
//                 <button onClick={changeCount}>click me</button>
//                 <a
//                     className="App-link"
//                     href="https://reactjs.org"
//                     target="_blank"
//                     rel="noopener noreferrer"
//                 >
//                     Learn React
//                 </a>
//             </header>
//         </div>
//     );
// }

export default App;

// mod_16_Frameworks_React/mod_16-3_VueJS/vueapp/src/App.vue
<script setup>
import Count from './components/Count.vue';
import {ref, watch} from 'vue';

const count = ref(2);

const items = ref([
  {
    number: 1,
    // initialCount: 10,
  },
  {
    number: 2,
    // initialCount: 20,
  },
  {
    number: 3,
    // initialCount: 30,
  },
  {
    number: 4,
    // initialCount: 40,
  },
]);

// function onCountChangeHandler(countNumber, newCountValue) {
//   console.log(`Value for ${countNumber} changed to ${newCountValue}!`);
// }

function onCountChangeHandler(newCountValue) {
  count.value = newCountValue;
}

function addNewCount() {
  const number = items.value.length > 0 ? (items.value[items.value.length - 1].number + 1) : 1;

  items.value.push({
    number: number
  });
  console.log(items.value);
}

watch(count, (newValue, oldValue) => {
  console.log(`Count value changed from ${oldValue} to ${newValue}`);
})

const message = ('Hello Alena Consul-adviser!');
</script>

<template>
  <p>{{ message }}</p>
  <br>
  <!--  <Count v-bind:initial-count="10" v-on:on-count-change="onCountChangeHandler" v-bind:number="1" />-->
  <!--  <Count :initial-count="20" @on-count-change="onCountChangeHandler" :number="2" />-->
  <!--  <Count :initial-count="30" @on-count-change="onCountChangeHandler" :number="3" />-->
  <!--  <Count v-for='item in items' :initial-count="item.initialCount" @on-count-change="onCountChangeHandler"-->
  <!--         :number="item.number" :key="item.number"/>-->
  <Count v-for='item in items' @on-count-change="onCountChangeHandler"
         :number="item.number" :count="count" key="item.number"/>
  <br>
  <div>
    <button @click="addNewCount">Add new count!</button>
  </div>

</template>

<style scoped>
</style>
